<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="Analogwerte" Id="{cb65ceda-4bf1-470d-b57d-3c08e6479214}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Analogwerte
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[AN.AQ_1 := AN.AI_1;]]></ST>
    </Implementation>
    <LineIds Name="Analogwerte">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>