<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="MAIN" Id="{9753ee2a-e609-4081-882e-52e8c65681cc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	B1 			AT %MX0.0: BOOL; 	// Lichtschranke draussen
	B2 			AT %MX0.1:	BOOL; 	//Lichtschranke drinnen 
	Auto 		AT %MB1: BYTE := 11; 		//Anzahl Autos
	Personen 	AT %MB2: BYTE := 22; 		// Anzahl Personen	

	Tiefgarage: Tiefgarage;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Tiefgarage();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="14" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>